[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "DJANGO_SETTINGS_MODULE=dpimedml.settings_production gunicorn dpimedml.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
DEBUG = "False"
PYTHON_VERSION = "3.11.8" 