# Generated by Django 4.2.23 on 2025-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("cscom", "Centre de Santé Communautaire"),
                            ("csref", "Centre de Santé de Référence"),
                            ("rehabilitation", "Centre de Réadaptation"),
                            ("hospital", "Hôpital"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Structure sanitaire",
                "verbose_name_plural": "Structures sanitaires",
            },
        ),
    ]
