# Generated by Django 4.2.23 on 2025-06-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["name"],
                "verbose_name": "Structure sanitaire",
                "verbose_name_plural": "Structures sanitaires",
            },
        ),
        migrations.RemoveField(
            model_name="facility",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="facility",
            name="city",
            field=models.CharField(
                default="Bamako", max_length=100, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="country",
            field=models.CharField(default="Mali", max_length=100, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="facility",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="region",
            field=models.CharField(
                default="Bamako", max_length=100, verbose_name="Région"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="year_established",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Année de création"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("CSCom", "Centre de Santé Communautaire"),
                    ("CSRef", "Centre de Santé de Référence"),
                    ("CR", "Centre de Réadaptation"),
                    ("H", "Hôpital"),
                    ("P", "Poste de Santé"),
                    ("A", "Autre"),
                ],
                max_length=10,
                verbose_name="Type de structure",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom de la structure"),
        ),
    ]
