# Generated by Django 4.2.23 on 2025-06-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "facilities",
            "0002_alter_facility_options_remove_facility_phone_number_and_more",
        ),
    ]

    operations = []
