# Generated by Django 4.2.23 on 2025-06-16 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20250616_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, default='Bamako', max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(blank=True, default='Mali', max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('CSCom', 'Centre de Santé Communautaire'), ('CSRef', 'Centre de Santé de Référence'), ('CR', 'Centre de Réadaptation'), ('H', 'Hôpital'), ('P', 'Poste de Santé'), ('A', 'Autre')], max_length=10, null=True, verbose_name='Type de structure'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
