# Generated by Django 4.2.23 on 2025-06-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0009_hospitalization_rehabilitationexercise_and_more"),
        ("accounts", "0001_initial"),
        ("facilities", "0004_alter_facility_address_alter_facility_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation spécialisée"),
                            ("rehabilitation", "Réadaptation"),
                            ("surgery", "Chirurgie"),
                            ("diagnostic", "Diagnostic spécialisé"),
                            ("hospitalization", "Hospitalisation"),
                            ("emergency", "Urgence"),
                            ("follow_up", "Suivi spécialisé"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("normal", "Normal"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "specialty_requested",
                    models.CharField(
                        max_length=100, verbose_name="Spécialité demandée"
                    ),
                ),
                (
                    "reason_for_referral",
                    models.TextField(verbose_name="Motif de référence"),
                ),
                ("clinical_summary", models.TextField(verbose_name="Résumé clinique")),
                (
                    "current_diagnosis",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Diagnostic actuel"
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, verbose_name="Médicaments actuels"),
                ),
                (
                    "relevant_history",
                    models.TextField(blank=True, verbose_name="Antécédents pertinents"),
                ),
                (
                    "specific_questions",
                    models.TextField(blank=True, verbose_name="Questions spécifiques"),
                ),
                (
                    "requested_services",
                    models.TextField(blank=True, verbose_name="Services demandés"),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date préférée"
                    ),
                ),
                (
                    "appointment_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Échéance RDV"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                            ("completed", "Complétée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date RDV confirmée"
                    ),
                ),
                (
                    "communication_notes",
                    models.TextField(blank=True, verbose_name="Notes de communication"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="patients.patient",
                    ),
                ),
                (
                    "receiving_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_referrals",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "receiving_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_referrals",
                        to="facilities.facility",
                    ),
                ),
                (
                    "referring_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_referrals",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "referring_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_referrals",
                        to="facilities.facility",
                    ),
                ),
                (
                    "supporting_documents",
                    models.ManyToManyField(
                        blank=True, related_name="referrals", to="patients.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Référence",
                "verbose_name_plural": "Références",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ReferralTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du modèle"),
                ),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation spécialisée"),
                            ("rehabilitation", "Réadaptation"),
                            ("surgery", "Chirurgie"),
                            ("diagnostic", "Diagnostic spécialisé"),
                            ("hospitalization", "Hospitalisation"),
                            ("emergency", "Urgence"),
                            ("follow_up", "Suivi spécialisé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Spécialité"),
                ),
                ("template_reason", models.TextField(verbose_name="Motif type")),
                (
                    "template_questions",
                    models.TextField(blank=True, verbose_name="Questions standard"),
                ),
                (
                    "required_documents",
                    models.TextField(blank=True, verbose_name="Documents requis"),
                ),
                (
                    "preparation_instructions",
                    models.TextField(
                        blank=True, verbose_name="Instructions de préparation"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de référence",
                "verbose_name_plural": "Modèles de références",
                "ordering": ["specialty", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReferralResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("acceptance", "Acceptation"),
                            ("rejection", "Refus"),
                            ("request_info", "Demande d'information"),
                            ("counter_proposal", "Contre-proposition"),
                            ("partial_acceptance", "Acceptation partielle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                (
                    "response_message",
                    models.TextField(verbose_name="Message de réponse"),
                ),
                (
                    "proposed_appointment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date RDV proposée"
                    ),
                ),
                (
                    "service_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lieu du service"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de refus"),
                ),
                (
                    "alternative_suggestion",
                    models.TextField(blank=True, verbose_name="Suggestion alternative"),
                ),
                (
                    "additional_info_needed",
                    models.TextField(
                        blank=True,
                        verbose_name="Informations supplémentaires nécessaires",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût estimé (CFA)",
                    ),
                ),
                (
                    "expected_duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Durée prévue"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(default=False, verbose_name="Suivi requis"),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(blank=True, verbose_name="Instructions de suivi"),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_referrals",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="referrals.referral",
                    ),
                ),
                (
                    "responding_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse à référence",
                "verbose_name_plural": "Réponses aux références",
                "ordering": ["-response_date"],
            },
        ),
        migrations.CreateModel(
            name="ReferralFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_date", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("successful", "Réussi"),
                            ("partially_successful", "Partiellement réussi"),
                            ("unsuccessful", "Non réussi"),
                            ("ongoing", "En cours"),
                            ("transferred", "Transféré ailleurs"),
                        ],
                        default="ongoing",
                        max_length=25,
                    ),
                ),
                (
                    "services_provided",
                    models.TextField(verbose_name="Services fournis"),
                ),
                (
                    "diagnosis_confirmation",
                    models.TextField(
                        blank=True, verbose_name="Confirmation diagnostique"
                    ),
                ),
                (
                    "treatment_provided",
                    models.TextField(blank=True, verbose_name="Traitement fourni"),
                ),
                (
                    "patient_satisfaction",
                    models.PositiveIntegerField(
                        blank=True, help_text="Note de 1 à 5", null=True
                    ),
                ),
                (
                    "patient_condition_improved",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="État amélioré"
                    ),
                ),
                (
                    "further_referrals_needed",
                    models.BooleanField(
                        default=False, verbose_name="Autres références nécessaires"
                    ),
                ),
                (
                    "continuing_care_plan",
                    models.TextField(blank=True, verbose_name="Plan de soins continus"),
                ),
                (
                    "referring_facility_feedback",
                    models.TextField(
                        blank=True, verbose_name="Commentaires établissement référent"
                    ),
                ),
                (
                    "receiving_facility_feedback",
                    models.TextField(
                        blank=True, verbose_name="Commentaires établissement receveur"
                    ),
                ),
                (
                    "timeliness_rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="Respect des délais (1-5)", null=True
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="Qualité communication (1-5)", null=True
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.PositiveIntegerField(
                        blank=True, help_text="Satisfaction globale (1-5)", null=True
                    ),
                ),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "referral",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up",
                        to="referrals.referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de référence",
                "verbose_name_plural": "Suivis de références",
            },
        ),
    ]
