# Generated by Django 4.2.23 on 2025-06-24 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0008_remove_patient_disability_type_and_more"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("medical_records", "Medical Records"),
                            ("appointment_history", "Appointment History"),
                            ("voucher_data", "Voucher Data"),
                            ("rehabilitation_plans", "Rehabilitation Plans"),
                            ("system_logs", "System Logs"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "retention_period_days",
                    models.IntegerField(help_text="Number of days to retain data"),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("success", models.BooleanField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="systemactivity",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemactivity",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemactivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("register", "Register"),
                    ("export", "Data Export"),
                    ("access", "Data Access"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SecurityAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("login_failed", "Failed Login"),
                            ("login_success", "Successful Login"),
                            ("password_change", "Password Change"),
                            ("data_access", "Data Access"),
                            ("permission_change", "Permission Change"),
                            ("account_locked", "Account Locked"),
                            ("gdpr_request", "GDPR Request"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Audit",
                "verbose_name_plural": "Security Audits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_processing", "Data Processing"),
                            ("medical_records", "Medical Records"),
                            ("sharing_partners", "Data Sharing with Partners"),
                            ("marketing", "Marketing Communications"),
                            ("research", "Medical Research"),
                        ],
                        max_length=30,
                    ),
                ),
                ("granted", models.BooleanField()),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legal_basis",
                    models.TextField(
                        help_text="Legal basis for processing (GDPR Article 6)"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revoked_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Consent",
                "verbose_name_plural": "Patient Consents",
                "ordering": ["-granted_at"],
            },
        ),
    ]
