# Generated by Django 4.2.23 on 2025-06-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        ("patients", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RehabilitationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("diagnosis", models.TextField()),
                ("goals", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Terminé"),
                            ("suspended", "Suspendu"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rehabilitation_plans",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescribing_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_plans",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de réadaptation",
                "verbose_name_plural": "Plans de réadaptation",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RehabilitationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField()),
                ("session_type", models.CharField(max_length=100)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("missed", "Manqué"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facilities.facility",
                    ),
                ),
                (
                    "rehabilitation_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="rehabilitation.rehabilitationplan",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="therapy_sessions",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance de réadaptation",
                "verbose_name_plural": "Séances de réadaptation",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="RehabilitationAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("findings", models.TextField()),
                ("recommendations", models.TextField()),
                (
                    "attachments",
                    models.FileField(
                        blank=True, null=True, upload_to="rehabilitation/assessments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "rehabilitation_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="rehabilitation.rehabilitationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de réadaptation",
                "verbose_name_plural": "Évaluations de réadaptation",
                "ordering": ["-assessment_date"],
            },
        ),
    ]
