# Generated by Django 4.2.23 on 2025-06-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rehabilitation", "0001_initial"),
    ]

    operations = []
