# Generated by Django 4.2.23 on 2025-06-23 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rehabilitation",
            "0003_alter_rehabilitationassessment_assessment_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="developmental_milestones",
            field=models.JSONField(
                blank=True, default=list, help_text="Étapes de développement atteintes"
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="family_satisfaction",
            field=models.IntegerField(
                default=3,
                help_text="Satisfaction familiale (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="functional_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Scores fonctionnels par domaine (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="overall_progress",
            field=models.IntegerField(
                default=3,
                help_text="Progression générale (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="risk_factors",
            field=models.JSONField(
                blank=True, default=list, help_text="Facteurs de risque identifiés"
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationassessment",
            name="who_growth_percentile",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentile de croissance OMS pour enfants 0-14 ans",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationplan",
            name="baseline_assessment",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Évaluation initiale des domaines fonctionnels (0-5)",
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationplan",
            name="expected_duration_weeks",
            field=models.PositiveIntegerField(
                default=12, help_text="Durée prévue du plan en semaines"
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationplan",
            name="family_involvement_score",
            field=models.IntegerField(
                default=3,
                help_text="Niveau d'implication familiale (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationplan",
            name="target_goals",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Objectifs cibles pour chaque domaine fonctionnel",
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationsession",
            name="exercises_completed",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Exercices réalisés pendant la séance",
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationsession",
            name="family_participation",
            field=models.BooleanField(
                default=False, help_text="Participation de la famille à la séance"
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationsession",
            name="next_session_recommendations",
            field=models.TextField(
                blank=True,
                help_text="Recommandations pour la prochaine séance",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationsession",
            name="patient_engagement",
            field=models.IntegerField(
                default=3,
                help_text="Niveau d'engagement du patient (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="rehabilitationsession",
            name="session_effectiveness",
            field=models.IntegerField(
                default=3,
                help_text="Efficacité de la séance (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rehabilitationsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("physiotherapy", "Kinésithérapie"),
                    ("occupational_therapy", "Ergothérapie"),
                    ("speech_therapy", "Orthophonie"),
                    ("psychological_support", "Soutien psychologique"),
                    ("family_education", "Éducation familiale"),
                    ("group_therapy", "Thérapie de groupe"),
                ],
                default="physiotherapy",
                help_text="Type de séance de réhabilitation",
                max_length=50,
            ),
        ),
    ]
