# Generated by Django 4.2.23 on 2025-06-23 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0004_alter_facility_address_alter_facility_city_and_more"),
        ("accounts", "0001_initial"),
        ("patients", "0006_icd10code_alter_medicalrecord_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom commercial du médicament", max_length=200
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        help_text="Dénomination commune internationale (DCI)",
                        max_length=200,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Comprimé"),
                            ("CAPSULE", "Gélule"),
                            ("SYRUP", "Sirop"),
                            ("SUSPENSION", "Suspension"),
                            ("INJECTION", "Injection"),
                            ("CREAM", "Crème"),
                            ("OINTMENT", "Pommade"),
                            ("DROPS", "Gouttes"),
                            ("INHALER", "Inhalateur"),
                            ("POWDER", "Poudre"),
                            ("OTHER", "Autre"),
                        ],
                        default="TABLET",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="ex: 250mg, 5ml, 100mg/5ml", max_length=100
                    ),
                ),
                ("unit", models.CharField(help_text="mg, ml, UI, etc.", max_length=50)),
                (
                    "is_pediatric_approved",
                    models.BooleanField(
                        default=True, help_text="Approuvé pour usage pédiatrique"
                    ),
                ),
                (
                    "min_age_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Âge minimum en mois", null=True
                    ),
                ),
                (
                    "max_age_years",
                    models.PositiveIntegerField(
                        blank=True, help_text="Âge maximum en années", null=True
                    ),
                ),
                (
                    "weight_based_dosing",
                    models.BooleanField(
                        default=True, help_text="Dosage basé sur le poids"
                    ),
                ),
                (
                    "default_dose_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Dose par kg de poids corporel",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_dose_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Dose maximale par jour",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "frequency_per_day",
                    models.PositiveIntegerField(
                        default=1, help_text="Fréquence par jour"
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Contre-indications"),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Effets secondaires"),
                ),
                (
                    "drug_interactions",
                    models.TextField(
                        blank=True, help_text="Interactions médicamenteuses"
                    ),
                ),
                (
                    "pregnancy_category",
                    models.CharField(
                        blank=True, help_text="Catégorie grossesse", max_length=2
                    ),
                ),
                (
                    "available_in_mali",
                    models.BooleanField(default=True, help_text="Disponible au Mali"),
                ),
                (
                    "essential_drug_list",
                    models.BooleanField(
                        default=False, help_text="Liste des médicaments essentiels"
                    ),
                ),
                (
                    "requires_special_storage",
                    models.CharField(
                        choices=[
                            ("ROOM_TEMP", "Température ambiante"),
                            ("COOL", "Endroit frais"),
                            ("REFRIGERATED", "Réfrigéré"),
                            ("FREEZER", "Congelé"),
                            ("DRY", "Endroit sec"),
                        ],
                        default="ROOM_TEMP",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Médicament",
                "verbose_name_plural": "Médicaments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color_code", models.CharField(default="#0C7C59", max_length=7)),
                ("icon", models.CharField(default="fa-pills", max_length=50)),
            ],
            options={
                "verbose_name": "Catégorie de médicament",
                "verbose_name_plural": "Catégories de médicaments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "diagnosis",
                    models.CharField(help_text="Diagnostic associé", max_length=500),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, help_text="Notes cliniques"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions pour le patient"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PRESCRIBED", "Prescrit"),
                            ("VALIDATED", "Validé"),
                            ("DISPENSED", "Délivré"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Élevé"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "prescribed_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validated_date", models.DateTimeField(blank=True, null=True)),
                ("dispensed_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "requires_authorization",
                    models.BooleanField(
                        default=False, help_text="Nécessite autorisation spéciale"
                    ),
                ),
                (
                    "covered_by_insurance",
                    models.BooleanField(
                        default=False, help_text="Couvert par assurance"
                    ),
                ),
                (
                    "voucher_required",
                    models.BooleanField(
                        default=False, help_text="Bon de prise en charge requis"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispensing_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_dispensed",
                        to="facilities.facility",
                    ),
                ),
                (
                    "dispensing_pharmacist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_prescriptions",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescribing_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_prescriptions",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "prescribing_facility",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_issued",
                        to="facilities.facility",
                    ),
                ),
                (
                    "validating_pharmacist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_prescriptions",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-prescribed_date"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom du protocole", max_length=200),
                ),
                ("description", models.TextField(help_text="Description du protocole")),
                ("min_age_months", models.PositiveIntegerField(blank=True, null=True)),
                ("max_age_months", models.PositiveIntegerField(blank=True, null=True)),
                ("conditions", models.TextField(help_text="Conditions d'application")),
                ("standard_instructions", models.TextField(blank=True)),
                (
                    "is_who_approved",
                    models.BooleanField(default=False, help_text="Approuvé par l'OMS"),
                ),
                (
                    "is_mali_standard",
                    models.BooleanField(default=False, help_text="Standard au Mali"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prescriptions.medicationcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocole de prescription",
                "verbose_name_plural": "Protocoles de prescription",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_dose_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "standard_frequency",
                    models.CharField(default="2 fois par jour", max_length=100),
                ),
                (
                    "standard_duration",
                    models.PositiveIntegerField(
                        default=7, help_text="Durée standard en jours"
                    ),
                ),
                ("standard_instructions", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.medication",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.prescriptiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="prescriptiontemplate",
            name="medications",
            field=models.ManyToManyField(
                through="prescriptions.TemplateMedication",
                to="prescriptions.medication",
            ),
        ),
        migrations.CreateModel(
            name="PrescriptionMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=3, help_text="Dose par prise", max_digits=10
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        help_text="Unité de dose (mg, ml, etc.)", max_length=20
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="Fréquence (ex: 3 fois par jour)", max_length=100
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Voie orale"),
                            ("TOPICAL", "Voie topique"),
                            ("INJECTION", "Injection"),
                            ("INHALATION", "Inhalation"),
                            ("NASAL", "Voie nasale"),
                            ("OPHTHALMIC", "Voie ophtalmique"),
                            ("OTIC", "Voie auriculaire"),
                            ("RECTAL", "Voie rectale"),
                            ("OTHER", "Autre"),
                        ],
                        default="ORAL",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Durée du traitement en jours"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantité totale à délivrer",
                        max_digits=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Instructions spécifiques (avant/après repas, etc.)"
                    ),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, help_text="Notes spéciales"),
                ),
                (
                    "substitution_allowed",
                    models.BooleanField(
                        default=True, help_text="Substitution générique autorisée"
                    ),
                ),
                (
                    "dispensed_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantité déjà délivrée",
                        max_digits=10,
                    ),
                ),
                ("is_dispensed", models.BooleanField(default=False)),
                ("dispensed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.medication",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament prescrit",
                "verbose_name_plural": "Médicaments prescrits",
            },
        ),
        migrations.AddField(
            model_name="medication",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions.medicationcategory",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.userprofile",
            ),
        ),
    ]
