# Generated by Django 4.2.23 on 2025-06-16 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vouchers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0004_alter_facility_address_alter_facility_city_and_more"),
        ("patients", "0003_alter_medicalrecord_options_alter_patient_options_and_more"),
        ("accounts", "0001_initial"),
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "expiry_date",
                    models.DateField(default=vouchers.models.get_default_expiry),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Émis"),
                            ("validated", "Validé"),
                            ("used", "Utilisé"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("validated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="vouchers/qr_codes/"
                    ),
                ),
                (
                    "issuing_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_vouchers",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "issuing_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_vouchers",
                        to="facilities.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="patients.patient",
                    ),
                ),
                (
                    "target_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_vouchers",
                        to="facilities.facility",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_vouchers",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de prise en charge",
                "verbose_name_plural": "Bons de prise en charge",
                "ordering": ["-issue_date"],
            },
        ),
    ]
