# Generated by Django 4.2.23 on 2025-06-16 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0003_alter_medicalrecord_options_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="guardian_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="guardian_phone",
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REPORT", "Rapport"),
                            ("PRESCRIPTION", "Prescription"),
                            ("IMAGING", "Imagerie"),
                            ("LAB", "Laboratoire"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="patients/documents/")),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document médical",
                "verbose_name_plural": "Documents médicaux",
                "ordering": ["-upload_date"],
            },
        ),
    ]
