# Generated by Django 4.2.23 on 2025-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_remove_patient_guardian_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="guardian_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
