# Generated by Django 4.2.23 on 2025-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_icd10code_alter_medicalrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="disability_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cerebral_palsy", "Paralysie cérébrale"),
                    ("intellectual_disability", "Déficience intellectuelle"),
                    (
                        "sensory_impairment",
                        "Déficiences sensorielles (visuelle/auditive)",
                    ),
                    ("physical_disability", "Handicap moteur/physique"),
                    ("autism_spectrum", "Troubles du spectre autistique"),
                    ("multiple_disabilities", "Handicaps multiples"),
                    ("developmental_delay", "Retard de développement"),
                    ("other", "Autre handicap"),
                ],
                help_text="Classification WHO ICF pour réhabilitation pédiatrique Mali",
                max_length=50,
                null=True,
                verbose_name="Type de handicap",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mali_district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commune_1", "Commune I"),
                    ("commune_2", "Commune II"),
                    ("commune_3", "Commune III"),
                    ("commune_4", "Commune IV"),
                    ("commune_5", "Commune V"),
                    ("commune_6", "Commune VI"),
                    ("other", "Autre district"),
                ],
                help_text="Localisation géographique pour accessibilité des soins",
                max_length=20,
                null=True,
                verbose_name="District de Bamako",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="severity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mild", "Léger"),
                    ("moderate", "Modéré"),
                    ("severe", "Sévère"),
                    ("profound", "Profond"),
                ],
                help_text="Évaluation clinique du degré de handicap",
                max_length=20,
                null=True,
                verbose_name="Niveau de sévérité",
            ),
        ),
    ]
