# Generated by Django 4.2.23 on 2025-06-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_add_mali_pediatric_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="disability_type",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mali_district",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="severity_level",
        ),
    ]
