# Generated by Django 4.2.23 on 2025-06-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_alter_facility_address_alter_facility_city_and_more"),
        ("accounts", "0001_initial"),
        ("patients", "0008_remove_patient_disability_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_date", models.DateTimeField()),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "admission_reason",
                    models.TextField(verbose_name="Motif d'admission"),
                ),
                (
                    "admission_diagnosis",
                    models.CharField(
                        max_length=500, verbose_name="Diagnostic d'admission"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        choices=[
                            ("pediatrie_A", "Pavillon Pédiatrique A"),
                            ("pediatrie_B", "Pavillon Pédiatrique B"),
                            ("readaptation", "Unité de Réadaptation"),
                            ("urgences", "Service des Urgences"),
                            ("chirurgie", "Chirurgie Pédiatrique"),
                            ("soins_intensifs", "Soins Intensifs"),
                        ],
                        max_length=20,
                        verbose_name="Chambre/Service",
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(max_length=10, verbose_name="Lit numéro"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("admitted", "Hospitalisé"),
                            ("discharged", "Sorti"),
                            ("transferred", "Transféré"),
                            ("deceased", "Décédé"),
                        ],
                        default="admitted",
                        max_length=20,
                    ),
                ),
                (
                    "discharge_diagnosis",
                    models.TextField(blank=True, verbose_name="Diagnostic de sortie"),
                ),
                (
                    "discharge_summary",
                    models.TextField(blank=True, verbose_name="Résumé de sortie"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "admitting_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admissions",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attended_patients",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalisation",
                "verbose_name_plural": "Hospitalisations",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="RehabilitationExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("instructions", models.TextField()),
                ("precautions", models.TextField(blank=True)),
                ("equipment_needed", models.CharField(blank=True, max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["difficulty_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalizationProgressNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Matin (6h-14h)"),
                            ("afternoon", "Après-midi (14h-22h)"),
                            ("night", "Nuit (22h-6h)"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("progress_note", models.TextField(verbose_name="Note d'évolution")),
                (
                    "treatment_administered",
                    models.TextField(
                        blank=True, verbose_name="Traitements administrés"
                    ),
                ),
                (
                    "complications",
                    models.TextField(
                        blank=True, verbose_name="Complications observées"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Température (°C)",
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fréquence cardiaque (bpm)"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fréquence respiratoire"
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="TA systolique"
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="TA diastolique"
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Saturation O2 (%)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "family_visit",
                    models.BooleanField(default=False, verbose_name="Visite famille"),
                ),
                (
                    "family_notes",
                    models.TextField(blank=True, verbose_name="Notes famille/tuteur"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "hospitalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_notes",
                        to="patients.hospitalization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note d'évolution",
                "verbose_name_plural": "Notes d'évolution",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="DischargeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discharge_type",
                    models.CharField(
                        choices=[
                            ("home", "Retour à domicile"),
                            ("transfer", "Transfert vers autre établissement"),
                            ("against_advice", "Sortie contre avis médical"),
                            ("deceased", "Décès"),
                            ("rehabilitation", "Centre de réadaptation"),
                        ],
                        max_length=20,
                        verbose_name="Type de sortie",
                    ),
                ),
                (
                    "discharge_condition",
                    models.CharField(
                        choices=[
                            ("improved", "Amélioré"),
                            ("stable", "Stable"),
                            ("worsened", "Aggravé"),
                            ("cured", "Guéri"),
                            ("chronic", "Chronique stabilisé"),
                        ],
                        max_length=20,
                        verbose_name="État à la sortie",
                    ),
                ),
                ("final_diagnosis", models.TextField(verbose_name="Diagnostic final")),
                (
                    "treatment_summary",
                    models.TextField(verbose_name="Résumé des traitements"),
                ),
                (
                    "procedures_performed",
                    models.TextField(blank=True, verbose_name="Procédures réalisées"),
                ),
                (
                    "complications_during_stay",
                    models.TextField(
                        blank=True, verbose_name="Complications pendant le séjour"
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(verbose_name="Instructions de suivi"),
                ),
                (
                    "medications_at_discharge",
                    models.TextField(
                        blank=True, verbose_name="Médicaments à la sortie"
                    ),
                ),
                (
                    "next_appointment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prochain RDV"
                    ),
                ),
                (
                    "next_appointment_service",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Service de suivi"
                    ),
                ),
                (
                    "transfer_reason",
                    models.TextField(blank=True, verbose_name="Motif de transfert"),
                ),
                (
                    "family_education_provided",
                    models.BooleanField(
                        default=False, verbose_name="Éducation famille fournie"
                    ),
                ),
                (
                    "family_education_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes éducation famille"
                    ),
                ),
                (
                    "rehabilitation_goals_achieved",
                    models.TextField(
                        blank=True, verbose_name="Objectifs de réadaptation atteints"
                    ),
                ),
                (
                    "home_exercise_program",
                    models.TextField(
                        blank=True, verbose_name="Programme d'exercices à domicile"
                    ),
                ),
                (
                    "assistive_devices_provided",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Aides techniques fournies",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "discharge_prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "hospitalization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_report",
                        to="patients.hospitalization",
                    ),
                ),
                (
                    "transfer_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facilities.facility",
                        verbose_name="Établissement de transfert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de sortie",
                "verbose_name_plural": "Rapports de sortie",
            },
        ),
    ]
